/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com;

/**
 *
 * @author Samsu
 */
import main.connection.Query;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import main.connection.Connect;
import java.sql.*;

public class DataDiskon extends javax.swing.JFrame {
    private DefaultTableModel tabMode;
    Connection conn = new Connect().connect();
    /**
     * Creates new form DataDiskon
     */
    
     protected void DataTable(){
        Object[] Baris = {"ID","KODE","DISKON","TERSEDIA"};
        tabMode = new DefaultTableModel(null, Baris);
        dataDiskons.setModel(tabMode);
        String sql = "SELECT * FROM diskon";
        try{
            java.sql.Statement state = conn.createStatement();
            ResultSet result = state.executeQuery(sql);
            while(result.next()){
                int nr = result.getInt("id");
                String kode = result.getString("kode");
                long diskon = result.getInt("discount");
                int tersedia = result.getInt("max");
                String [] data = {String.valueOf(nr),kode,String.valueOf(diskon) + "%",String.valueOf(tersedia)};
                tabMode.addRow(data);
            }
        }catch(Exception er){
            System.out.println(er);
        }
    }
    
    public DataDiskon() {
        initComponents();
        DataTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dataDiskons = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        diskon = new javax.swing.JTextField();
        kodeDiskon = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        maxDiskon = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        searchQ = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Master Diskon");
        setMinimumSize(new java.awt.Dimension(700, 500));
        setResizable(false);

        dataDiskons.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "KODE", "DISKON", "BATAS PENGGUNA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dataDiskons.setEditingRow(1);
        dataDiskons.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataDiskonsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dataDiskons);
        if (dataDiskons.getColumnModel().getColumnCount() > 0) {
            dataDiskons.getColumnModel().getColumn(0).setResizable(false);
            dataDiskons.getColumnModel().getColumn(1).setResizable(false);
            dataDiskons.getColumnModel().getColumn(2).setResizable(false);
            dataDiskons.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel1.setText("KODE DISKON");

        jLabel2.setText("DIKON (%)");

        jLabel3.setText("BATAS PENGGUNA");

        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.setVisible(false);

        jButton4.setText("Update");
        jButton4.setVisible(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        searchQ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchQKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(kodeDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(diskon, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(maxDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(searchQ, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kodeDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diskon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(searchQ, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Query main = new Query();
        boolean result = main.InsertDataDiskon(kodeDiskon.getText(),Integer.valueOf(diskon.getText()),Integer.valueOf(maxDiskon.getText()));
        if(result){
            JOptionPane.showMessageDialog(this,"Berhasil Buat Diskon");
            kodeDiskon.setText("");
            diskon.setText("");
            maxDiskon.setText("");
            DataTable();
        }else{
            JOptionPane.showMessageDialog(this,"Gagal Buat Diskon");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void dataDiskonsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataDiskonsMouseClicked
        // TODO add your handling code here:
        this.jButton3.setVisible(true);
        this.jButton4.setVisible(true);
        this.jButton1.setVisible(false);
        int bar = dataDiskons.getSelectedRow();
        String id = dataDiskons.getValueAt(bar,0).toString();
        String kode = dataDiskons.getValueAt(bar,1).toString();
        String diskons = dataDiskons.getValueAt(bar,2).toString();
        String batas = dataDiskons.getValueAt(bar,3).toString();
        kodeDiskon.setText(kode);
        diskon.setText(diskons);
        maxDiskon.setText(batas);
    }//GEN-LAST:event_dataDiskonsMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.jButton3.setVisible(false);
        this.jButton4.setVisible(false);
        this.jButton1.setVisible(true);
        kodeDiskon.setText("");
        diskon.setText("");
        maxDiskon.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Query main = new Query();
        int bar = dataDiskons.getSelectedRow();
        String id = dataDiskons.getValueAt(bar,0).toString();
        boolean result = main.UpdateDataDiskon(Integer.valueOf(id),kodeDiskon.getText(),Integer.valueOf(diskon.getText()),Integer.valueOf(maxDiskon.getText()));
        if(result){
            JOptionPane.showMessageDialog(this,"Diskon Berhasil Update");
            kodeDiskon.setText("");
            diskon.setText("");
            maxDiskon.setText("");
            DataTable();
            this.jButton3.setVisible(false);
            this.jButton4.setVisible(false);
            this.jButton1.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this,"Diskon Gagal Update");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void searchQKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchQKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER){
            String q = searchQ.getText();
            Object[] Baris = {"ID","KODE","DISKON","TERSEDIA"};
            tabMode = new DefaultTableModel(null, Baris);
            dataDiskons.setModel(tabMode);
            String sql = "SELECT * FROM diskon WHERE kode LIKE ?";
            try{
                PreparedStatement state = conn.prepareStatement(sql);
                state.setString(1,"%" + q + "%");
                ResultSet result = state.executeQuery();
                while(result.next()){
                    int nr = result.getInt("id");
                    String kode = result.getString("kode");
                    long diskon = result.getInt("discount");
                    int tersedia = result.getInt("max");
                    String [] data = {String.valueOf(nr),kode,String.valueOf(diskon),String.valueOf(tersedia)};
                    tabMode.addRow(data);
                }
            }catch(Exception er){
                System.out.println(er);
            }
        }
    }//GEN-LAST:event_searchQKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataDiskon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable dataDiskons;
    private javax.swing.JTextField diskon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kodeDiskon;
    private javax.swing.JTextField maxDiskon;
    private javax.swing.JTextField searchQ;
    // End of variables declaration//GEN-END:variables
}
