/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com;

/**
 *
 * @author fdlik
 */


import main.connection.Query;
import main.connection.Connect;
import main.reports.BuktiReservasiInvoice;

import java.sql.*;
import java.sql.Timestamp;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JOptionPane;

public class Pembayaran extends javax.swing.JFrame {
private Connection conn = new Connect().connect();
    /**
     * Creates new form Pembayaran
     */
    public Pembayaran() {
        initComponents();
    }
    
    public static String formatRupiah(double amount) {
        Locale indonesia = new Locale("id", "ID");
        NumberFormat formatter = NumberFormat.getCurrencyInstance(indonesia);
        return formatter.format(amount);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kodereservasi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        diskon = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jenispembayaran = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jeniskamar = new javax.swing.JLabel();
        harga = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        harga2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 650));

        kodereservasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodereservasiActionPerformed(evt);
            }
        });

        jLabel1.setText("Kede Reservasi");

        jLabel2.setText("Total Bayar");

        jButton1.setText("Cek");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Jenis Kamar");

        jLabel4.setText("Kode Diskon");

        diskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diskonActionPerformed(evt);
            }
        });

        jLabel5.setText("Jenis Pembayaran");

        jenispembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BCA", "MANDIRI", "BRI", "CASH" }));
        jenispembayaran.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jenispembayaranItemStateChanged(evt);
            }
        });
        jenispembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jenispembayaranMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jenispembayaranMousePressed(evt);
            }
        });
        jenispembayaran.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jenispembayaranCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jenispembayaranInputMethodTextChanged(evt);
            }
        });
        jenispembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenispembayaranActionPerformed(evt);
            }
        });
        jenispembayaran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jenispembayaranKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jenispembayaranKeyReleased(evt);
            }
        });

        jButton2.setText("SIMPAN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jeniskamar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jeniskamar.setText("-");

        harga.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        harga.setText("-");

        jButton3.setText("Cek");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        harga2.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jeniskamar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jenispembayaran, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(kodereservasi, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(diskon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(jButton3))))
                        .addContainerGap(373, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(harga, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(harga2)
                        .addGap(592, 592, 592))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kodereservasi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(harga2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jeniskamar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(diskon)
                            .addComponent(jButton3))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jenispembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(338, 338, 338))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String code =kodereservasi.getText();
        boolean hasil= new Query().Checkkodereservasi(code);
        if(hasil){
        try{
            String sql = "SELECT book.*, room.nomor_ruangan, room.harga, room.type, room.kapasitas FROM book JOIN room ON book.room = room.id WHERE kode_reservasi = ?";
            PreparedStatement state = conn.prepareStatement(sql);
            state.setString(1,code);
            ResultSet result = state.executeQuery();
            
            if(result.next()){
                int pay = Integer.valueOf(result.getString("harga"));
                Timestamp timestamp1 = result.getTimestamp("tanggal_masuk"); 
                Timestamp timestamp2 = result.getTimestamp("tanggal_keluar");
                long diffInMillies = Math.abs(timestamp2.getTime() - timestamp1.getTime());
                long diffInDays = TimeUnit.DAYS.convert(diffInMillies, TimeUnit.MILLISECONDS);  
                harga2.setText(String.valueOf(pay*diffInDays));
                harga.setText(String.valueOf(formatRupiah(Double.valueOf(pay * diffInDays))));
                jeniskamar.setText(result.getString("type"));
            }
            
        }catch(Exception err){
            System.out.println(err);
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void kodereservasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodereservasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodereservasiActionPerformed

    private void diskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diskonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diskonActionPerformed

    private void jenispembayaranItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jenispembayaranItemStateChanged
        // TODO add your handling code here:
        // hersss

    }//GEN-LAST:event_jenispembayaranItemStateChanged

    private void jenispembayaranMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jenispembayaranMouseEntered

    }//GEN-LAST:event_jenispembayaranMouseEntered

    private void jenispembayaranMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jenispembayaranMousePressed

    }//GEN-LAST:event_jenispembayaranMousePressed

    private void jenispembayaranCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jenispembayaranCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jenispembayaranCaretPositionChanged

    private void jenispembayaranInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jenispembayaranInputMethodTextChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_jenispembayaranInputMethodTextChanged

    private void jenispembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenispembayaranActionPerformed
        // TODO add your handling code here:
//        System.out.println(jenispembayaran.getSelectedItem());
//        try{
//            String sql = "SELECT * FROM room WHERE type LIKE ? AND jumlah_kamar > 0";
//            PreparedStatement state = conn.prepareStatement(sql);
//            state.setString(1,"%" +jenispembayaran.getSelectedItem()+"%");
//            ResultSet result = state.executeQuery();
//            if(result.next()){
//                List<String> dataList = new ArrayList<>();
//                do {
//                    String formattedPrice = this.formatRupiah(Double.valueOf(result.getString("harga"))) + " / Malam " +
//                    "(" + result.getInt("kapasitas") + " Orang)" + " #" + result.getInt("id");
//                    dataList.add(formattedPrice);
//                } while (result.next());
//                String[] data = dataList.toArray(new String[0]);
//                harga.setModel(new javax.swing.DefaultComboBoxModel<>(data));
//            }else{
//                System.out.println("Data Tidak Di Temukan");
//                harga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
//            }
//        }catch(Exception Er){
//            System.out.println(Er);
//        }
    }//GEN-LAST:event_jenispembayaranActionPerformed

    private void jenispembayaranKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jenispembayaranKeyPressed

    }//GEN-LAST:event_jenispembayaranKeyPressed

    private void jenispembayaranKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jenispembayaranKeyReleased

    }//GEN-LAST:event_jenispembayaranKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String kode = kodereservasi.getText();
        String harga_ = harga.getText();
        String jenis = jeniskamar.getText();
        boolean hasil;
        String payment = String.valueOf(jenispembayaran.getSelectedItem());
        if(diskon.getText().length() > 0){
            Query main = new Query();
            Query.GetDisc getResult = main.GetKodeDiskon(diskon.getText());
            if(getResult != null){
                hasil = new Query().InsertDataPembayaran(kode,getResult.getId(),payment);
                if(hasil){
                    JOptionPane.showMessageDialog(null, "Pembayaran Telah Berhasil Dilakukan");
                    this.dispose();
                    new BuktiReservasiInvoice().Reports();
                }
            }
        }else{
            hasil =  new Query().InsertDataPembayaran(kode,0,payment);
            if(hasil){
               JOptionPane.showMessageDialog(null, "Pembayaran Telah Berhasil Dilakukan");
            }
        }
        
        
                                     
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String promo;
        if(diskon.getText().length() > 0){
            Query main = new Query();
            Query.GetDisc getResult = main.GetKodeDiskon(diskon.getText());
            if(getResult != null){
                int disc = getResult.getDisc();               
                double hasil = ((double) disc / 100) * Integer.valueOf(harga2.getText());
                harga.setText(String.valueOf(formatRupiah(Integer.valueOf(harga2.getText()) - hasil)));
            }
        }else{
            promo = "0";
        }        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField diskon;
    private javax.swing.JLabel harga;
    private javax.swing.JLabel harga2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jeniskamar;
    private javax.swing.JComboBox<String> jenispembayaran;
    private javax.swing.JTextField kodereservasi;
    // End of variables declaration//GEN-END:variables
}
