/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com;

/**
 *
 * @author Samsu
 */
import main.connection.Query;
import javax.swing.JOptionPane;
import main.connection.Connect;
import java.sql.*;
import java.text.NumberFormat;
import java.text.DecimalFormat;
import java.util.Locale;
import java.util.List;
import java.util.ArrayList;
import java.util.Random;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Calendar;

import main.reports.BuktiReservasi;

public class Reservasi extends javax.swing.JFrame {
    private Connection conn = new Connect().connect();
    /**
     * Creates new form Reservasi
     */
    private static String GenerateKodeReservasi(){
        String charset = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"; // karakter yang digunakan untuk kode
        StringBuilder kode = new StringBuilder(6);
        Random random = new Random();
        
        // Menghasilkan kode acak berdasarkan panjang yang ditentukan
        for (int i = 0; i < 6; i++) {
            int index = random.nextInt(charset.length()); // Pilih indeks acak dari charset
            kode.append(charset.charAt(index)); // Tambahkan karakter acak ke kode
        }
        return "RSV-HTL" + kode.toString();
    }
    private static String formatRupiah(double amount){
         // Locale Indonesia
        Locale locale = new Locale("id", "ID");
        DecimalFormat decimalFormat = (DecimalFormat) NumberFormat.getCurrencyInstance(locale);
        decimalFormat.applyPattern("Rp #,##0.00");
        // Memformat angka dan mengembalikan string yang sudah diformat
        return decimalFormat.format(amount);
    }
    
    public Reservasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nikP = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        total_malam = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        harga = new javax.swing.JComboBox<>();
        rom = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        idRom = new javax.swing.JTextField();
        tgl_checkin = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));
        setResizable(false);

        jLabel1.setText("HARGA");

        jButton1.setText("CHECK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("NIK /  PASSPORT");

        total_malam.setText("1");
        total_malam.setAlignmentX(0.0F);
        total_malam.setAlignmentY(0.0F);
        total_malam.setEnabled(false);
        total_malam.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jLabel5.setText("TANGGAL");

        jLabel6.setText("TOTAL MALAM");

        harga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        harga.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                hargaItemStateChanged(evt);
            }
        });
        harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaActionPerformed(evt);
            }
        });

        rom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "STANDAR", "VIP", "VVIP", "LUXURY" }));
        rom.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                romItemStateChanged(evt);
            }
        });
        rom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                romMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                romMousePressed(evt);
            }
        });
        rom.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                romCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                romInputMethodTextChanged(evt);
            }
        });
        rom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                romActionPerformed(evt);
            }
        });
        rom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                romKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                romKeyReleased(evt);
            }
        });

        jLabel7.setText("KAMAR");

        jButton2.setText("SIMPAN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("-");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("+");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        idRom.setText("jTextField1");
        idRom.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(total_malam, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(harga, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(idRom, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(333, 333, 333))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(nikP, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(288, 288, 288))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rom, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(323, 323, 323))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tgl_checkin, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(599, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nikP, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(tgl_checkin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total_malam, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rom, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idRom, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(258, 258, 258))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(534, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Query main = new Query();
        try{
            boolean t = main.CheckTamuOnReservasi(Integer.valueOf(nikP.getText()));
            if(t){
                jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/assets/true.png")));
            }else{
                jLabel4.setIcon(null);
                JOptionPane.showMessageDialog(null, "No Identitas Tidak Valid");
            }
        }catch(Exception er){
            jLabel4.setIcon(null);
            JOptionPane.showMessageDialog(null, "No Identitas Tidak Valid");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            Query main = new Query();
            int NIK = Integer.valueOf(nikP.getText());
            SimpleDateFormat sdf = new SimpleDateFormat("MMM dd, yyyy");
            Date dateIn = tgl_checkin.getDate();
            long tmstmp = dateIn.getTime(); 
            int totalNight = Integer.valueOf(total_malam.getText());
            String input = String.valueOf(harga.getSelectedItem());
            int index = input.indexOf('#');
            int rom = Integer.valueOf(input.substring(index + 1));
            
            // Hitung Tnggal Keluar
            Calendar calendar = Calendar.getInstance();
            
            calendar.setTimeInMillis(tmstmp);
            
            calendar.add(Calendar.DAY_OF_MONTH, totalNight);
            Date tgl_keluar = calendar.getTime();
            long tgl_out = calendar.getTime().getTime();
            boolean result = main.InsertDataReservasi(this.GenerateKodeReservasi(),NIK,tmstmp,totalNight,rom,tgl_out);
            if(result){
                JOptionPane.showMessageDialog(null, "Reservasi Berhasil Dibuat");
                this.dispose();
                // Tampilkan Bukti
                BuktiReservasi report = new BuktiReservasi();
                report.ReportBuktiBooking();
            }else{
            }
        }catch(Exception er){
            System.out.println(er);
        }
        
        //
    }//GEN-LAST:event_jButton2ActionPerformed

    private void romInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_romInputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_romInputMethodTextChanged

    private void romCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_romCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_romCaretPositionChanged

    private void romKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_romKeyPressed

    }//GEN-LAST:event_romKeyPressed

    private void romMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_romMouseEntered
        
    }//GEN-LAST:event_romMouseEntered

    private void romMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_romMousePressed
        
    }//GEN-LAST:event_romMousePressed

    private void romKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_romKeyReleased
      
    }//GEN-LAST:event_romKeyReleased

    private void romItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_romItemStateChanged
        // TODO add your handling code here:
        // hersss
        
    }//GEN-LAST:event_romItemStateChanged

    private void hargaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_hargaItemStateChanged
        // TODO add your handling code here:
//        String input = String.valueOf(harga.getSelectedItem());
//        int index = input.indexOf('#');
//        idRom.setText(input.substring(index + 1));
//        System.out.println(input.substring(index + 1));
    }//GEN-LAST:event_hargaItemStateChanged

    private void hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaActionPerformed
        // TODO add your handling code here:
        String input = String.valueOf(harga.getSelectedItem());
        int index = input.indexOf('#');
        idRom.setText(input.substring(index + 1));
        System.out.println(input.substring(index + 1));
    }//GEN-LAST:event_hargaActionPerformed

    private void romActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_romActionPerformed
        // TODO add your handling code here:
        System.out.println(rom.getSelectedItem());
        try{
            String sql = "SELECT * FROM room WHERE type LIKE ? AND jumlah_kamar > 0";
            PreparedStatement state = conn.prepareStatement(sql);
            state.setString(1,"%" +rom.getSelectedItem()+"%");
            ResultSet result = state.executeQuery();
            if(result.next()){
                List<String> dataList = new ArrayList<>();
                do {
                    String formattedPrice = this.formatRupiah(Double.valueOf(result.getString("harga"))) + " / Malam " +
                                             "(" + result.getInt("kapasitas") + " Orang)" + " #" + result.getInt("id");
                    dataList.add(formattedPrice);
                } while (result.next());
                String[] data = dataList.toArray(new String[0]);
                harga.setModel(new javax.swing.DefaultComboBoxModel<>(data));
            }else{
                System.out.println("Data Tidak Di Temukan");                
                 harga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
            }
        }catch(Exception Er){
            System.out.println(Er);
        }
    }//GEN-LAST:event_romActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        // Tambah Total Malam
        int total = Integer.valueOf(total_malam.getText()) + 1;        
        total_malam.setText(String.valueOf(total));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        // Kurang Total Malam
        int total = Integer.valueOf(total_malam.getText());
        if(total != 1){
            total_malam.setText(String.valueOf(total - 1));
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reservasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> harga;
    private javax.swing.JTextField idRom;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nikP;
    private javax.swing.JComboBox<String> rom;
    private com.toedter.calendar.JDateChooser tgl_checkin;
    private javax.swing.JTextField total_malam;
    // End of variables declaration//GEN-END:variables
}
